"use client";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Leaf, Menu, X, User, LogOut } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";
import { ModeToggle } from "@/components/mode-toggle";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, } from "@/components/ui/dropdown-menu";
export function SiteHeader() {
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const { user, signOut, isAdmin } = useAuth();
    return (_jsx("header", { className: "sticky top-0 z-50 w-full border-b border-border bg-background/95 backdrop-blur supports-backdrop-filter:bg-background/60", children: _jsxs("div", { className: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex h-16 items-center justify-between gap-8", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2 hover:opacity-80 transition-opacity shrink-0", children: [_jsx("div", { className: "flex h-8 w-8 items-center justify-center rounded-lg bg-green-100", children: _jsx(Leaf, { className: "h-5 w-5 text-green-800" }) }), _jsxs("span", { className: "text-xl font-bold text-foreground", children: ["Green", _jsx("span", { className: "text-primary", children: "UM" })] })] }), _jsxs("nav", { className: "hidden md:flex items-center gap-8 flex-1 justify-center", children: [_jsx(Link, { to: "/", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", children: "Home" }), _jsx(Link, { to: "/events", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", children: "Events" }), _jsx(Link, { to: "/leaderboard", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", children: "Leaderboard" }), _jsx(Link, { to: "/about", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", children: "About" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-3", children: [user ? (_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "flex flex-col items-end mr-1", children: [_jsx("span", { className: "text-xs font-semibold text-gray-900 dark:text-gray-100 leading-none", children: user.email?.split("@")[0]
                                                        ? user.email.split("@")[0].charAt(0).toUpperCase() +
                                                            user.email.split("@")[0].slice(1)
                                                        : "" }), _jsx("span", { className: "text-[10px] text-gray-500 dark:text-gray-400 font-medium mt-0.5 tracking-tight", children: isAdmin ? "Administrator" : "Community Member" })] }), _jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsx("button", { className: "bg-green-100 dark:bg-green-900 p-2 rounded-lg text-green-700 dark:text-green-300 hover:bg-green-200 dark:hover:bg-green-800 transition-all", children: _jsx(User, { className: "w-5 h-5" }) }) }), _jsx(DropdownMenuContent, { align: "end", children: _jsxs(DropdownMenuItem, { onClick: () => signOut(), variant: "destructive", children: [_jsx(LogOut, { className: "w-4 h-4" }), "Log out"] }) })] })] })) : (_jsxs(_Fragment, { children: [_jsx(Button, { variant: "ghost", asChild: true, children: _jsx(Link, { to: "/auth", children: "Login" }) }), _jsx(Button, { asChild: true, className: "gap-2 bg-green-800 text-white", children: _jsxs(Link, { to: "/auth", children: ["Sign Up", _jsx(Leaf, { className: "h-4 w-4" })] }) })] })), _jsx(ModeToggle, {})] }), _jsx("button", { className: "md:hidden p-2 text-muted-foreground hover:text-foreground", onClick: () => setMobileMenuOpen(!mobileMenuOpen), "aria-label": "Toggle menu", children: mobileMenuOpen ? (_jsx(X, { className: "h-6 w-6" })) : (_jsx(Menu, { className: "h-6 w-6" })) })] }), mobileMenuOpen && (_jsx("div", { className: "md:hidden py-4 border-t border-border", children: _jsxs("nav", { className: "flex flex-col gap-4", children: [_jsx(Link, { to: "/", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", onClick: () => setMobileMenuOpen(false), children: "Home" }), _jsx(Link, { to: "/events", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", onClick: () => setMobileMenuOpen(false), children: "Events" }), _jsx(Link, { to: "/leaderboard", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", onClick: () => setMobileMenuOpen(false), children: "Leaderboard" }), _jsx(Link, { to: "/about", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", onClick: () => setMobileMenuOpen(false), children: "About" }), _jsxs("div", { className: "flex flex-col gap-2 pt-4 border-t border-border", children: [user ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "flex flex-col items-start mb-2", children: [_jsx("span", { className: "text-xs font-semibold text-gray-900 dark:text-gray-100 leading-none", children: user.email?.split("@")[0]
                                                            ? user.email.split("@")[0].charAt(0).toUpperCase() +
                                                                user.email.split("@")[0].slice(1)
                                                            : "" }), _jsx("span", { className: "text-[10px] text-gray-500 dark:text-gray-400 font-medium mt-0.5 tracking-tight", children: isAdmin ? "Administrator" : "Community Member" })] }), _jsxs(Button, { variant: "destructive", onClick: () => {
                                                    signOut();
                                                    setMobileMenuOpen(false);
                                                }, className: "gap-2", children: [_jsx(LogOut, { className: "w-4 h-4" }), "Log out"] })] })) : (_jsxs(_Fragment, { children: [_jsx(Button, { variant: "outline", asChild: true, children: _jsx(Link, { to: "/auth", onClick: () => setMobileMenuOpen(false), children: "Login" }) }), _jsx(Button, { asChild: true, className: "gap-2 bg-green-800 text-white", children: _jsxs(Link, { to: "/auth", onClick: () => setMobileMenuOpen(false), children: ["Sign Up", _jsx(Leaf, { className: "h-4 w-4" })] }) })] })), _jsx("div", { className: "flex justify-center pt-2", children: _jsx(ModeToggle, {}) })] })] }) }))] }) }));
}
