export const leaderboardData = [
  {
    rank: 1,
    name: "Sarah Chen",
    username: "sarahc",
    points: 15420,
    badges: 24,
    avatar: "/woman-profile.png",
  },
  {
    rank: 2,
    name: "Marcus Johnson",
    username: "marcusj",
    points: 14850,
    badges: 22,
    avatar: "/man-profile.png",
  },
  {
    rank: 3,
    name: "Aisha Patel",
    username: "aishaP",
    points: 13920,
    badges: 21,
    avatar: "/woman-profile-two.png",
  },
  {
    rank: 4,
    name: "David Kim",
    username: "davidk",
    points: 12680,
    badges: 19,
    avatar: "/man-profile-2.png",
  },
  {
    rank: 5,
    name: "Emma Rodriguez",
    username: "emmar",
    points: 11540,
    badges: 18,
    avatar: "/woman-profile-3.png",
  },
  {
    rank: 6,
    name: "James Wilson",
    username: "jamesw",
    points: 10820,
    badges: 17,
    avatar: "/man-profile-3.png",
  },
  {
    rank: 7,
    name: "Fatima Hassan",
    username: "fatimah",
    points: 9940,
    badges: 16,
    avatar: "/woman-profile-4.png",
  },
  {
    rank: 8,
    name: "Chen Wei",
    username: "chenw",
    points: 9120,
    badges: 15,
    avatar: "/man-profile-4.png",
  },
  {
    rank: 9,
    name: "Olivia Martinez",
    username: "oliviam",
    points: 8650,
    badges: 14,
    avatar: "/woman-profile-5.png",
  },
  {
    rank: 10,
    name: "Michael Brown",
    username: "michaelb",
    points: 8240,
    badges: 13,
    avatar: "/man-profile-5.png",
  },
  {
    rank: 11,
    name: "Priya Singh",
    username: "priyas",
    points: 7890,
    badges: 12,
    avatar: "/woman-profile-6.png",
  },
  {
    rank: 12,
    name: "Alex Thompson",
    username: "alext",
    points: 7320,
    badges: 11,
    avatar: "/diverse-person-profiles.png",
  },
  {
    rank: 13,
    name: "Sofia Garcia",
    username: "sofiag",
    points: 6950,
    badges: 10,
    avatar: "/woman-profile-7.png",
  },
  {
    rank: 14,
    name: "Ryan O'Connor",
    username: "ryano",
    points: 6540,
    badges: 9,
    avatar: "/man-profile-6.png",
  },
  {
    rank: 15,
    name: "Zara Ahmed",
    username: "zaraa",
    points: 6180,
    badges: 8,
    avatar: "/woman-profile-8.png",
  },
];
